### ISSUE TITLE
Repo visibility

### ISSUE THREAD

**Issue by andriytyurnikov** [8x8Cloud/better_exception_handling#1]
Please make this repo visible for deployment scripts and machines

**Comment by Nowaker** [comment]
Or just public? There's nothing to hide here.

**Comment by andriytyurnikov** [comment]
@Nowaker I would prefer public too, but visibility is minimal way to go here

**Comment by DragosIorgulescu** [comment]
@andriytyurnikov why is visibility the minimal way to go? I agree that we have no reason to keep this private.

@andriytyurnikov @rljohnsn any reason why we would keep the better exception handling gem extracted by @andriytyurnikov private?

**Comment by andriytyurnikov** [comment]
@DragosIorgulescu, @rljohnsn  no reason - just being paranoid. Having it public will be fine with me (and will simplify travis setup ;-)

**Comment by Nowaker** [comment]
Made it public. Blame me if it was a bad move. ;)

**Comment by schwaberdoodles** [comment]
Public is fine. Maybe just change the github repo to public so it can be distributed directly from GitHub,
